AdvancedViewProject/urls.py
from django.contrib import admin
from django.urls import path, include
from store import views  # アプリフォルダstoreにあるviewsをimoortしている

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls')),
    path('user/', include('user.urls')),
]

# handlerにviews.pyの関数を代入
handler404 = views.page_not_found
handler500 = views.server_error

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('item_list/', views.item_list, name='item_list'),
    path('item_detail/<int:id>', views.item_detail, name='item_detail'),
    path('to_google/', views.to_google, name='to_google'),
    path('one_item/', views.one_item, name='one_item'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('user_list/', views.user_list, name='user_list'),
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('info/', views.info, name='info'),
]

store/models.py
from django.db import models


# Create your models here.
class Items(models.Model):
    name = models.CharField(max_length=50, verbose_name='商品名')
    price = models.IntegerField(verbose_name='価格')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'items'
        verbose_name = verbose_name_plural = '販売商品'

user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User


# デフォルトのユーザーテーブルにwebsiteとpictureの項目を追加した
# OneToOneフィールドで紐づける
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.FileField(upload_to='user/', blank=True)

    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.models import User
from user.models import Profile


# djangoのデフォルトのユーザーモデルを使ったモデルフォーム
class UserForm(forms.ModelForm):
    username = forms.CharField(label='名前')
    email = forms.EmailField(label='メールアドレス')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
    # パスワード再確認フォーム
    confirm_password = forms.CharField(
        label='パスワード再入力', widget=forms.PasswordInput()
        )

    # ２回入力したパスワードが一致するかバリデーション
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが一致しません')

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


# models.pyで定義したProfileモデルのモデルフォーム
class ProfileForm(forms.ModelForm):
    website = forms.URLField(label='ホームページ')
    picture = forms.FileField(label='写真')

    class Meta():
        model = Profile
        fields = ('website', 'picture')


class LoginForm(forms.Form):
    username = forms.CharField(label='名前', max_length=150)
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput())

store/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Items
from django.http import Http404


# Create your views here.


def item_list(request):
    items = Items.objects.all()
    items = get_list_or_404(Items, pk__gt=2)  # pkが2より大きいものの指定。なければ404になる
    return render(request, 'store/item_list.html', context={
        'items': items
    })


# サーバーエラーテスト用
# def item_list(request):
#     items = Items.objects.all()
#     return render(request, 'store/itemlist.html', context={
#         'items': items
#     })


def item_detail(request, id):
    if id == 0:
        raise Http404
    # item = Items.objects.filter(pk=id).first()
    item = get_object_or_404(Items, pk=id)  # g~_or_404のテスト用 存在しないidだと404が出る

    # idでitemを取得できなかったらリストにリダイレクトさせる
    if item is None:
        return redirect('store:item_list')
    return render(request, 'store/item_detail.html', context={
        'item': item
    })


def to_google(request):
    return redirect('https://www.google.com')


# templateをrenderするのではなく、app_name=storeのurlname=item_detailにリダイレクトさせる
def one_item(request):
    # id=1を引数で渡してitem_detail関数の実行
    return redirect('store:item_detail', id=1)


def page_not_found(request, exception):
    return render(request, 'store/404.html', status=404)  # 404をステータスにとらないと、アクセスログに200と表示されてしまう
    # return redirect('store:item_list')  # 強制的にリストページにリダイレクトさせる


def server_error(request):
    return render(request, 'store/500.html', status=500)

user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user.forms import UserForm, ProfileForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError

# Create your views here.


def user_list(request):
    return render(request, 'user/user_list.html')


def index(request):
    return render(request, 'user/index.html')


def register(request):
    user_form = UserForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None, request.FILES or None)

    if user_form.is_valid() and profile_form.is_valid():
        user = user_form.save(commit=False)  # バリデーションのためにDBに登録せずインスタンスを取り出す
        try:
            # バリデーションを実行
            validate_password(user_form.cleaned_data.get('password'), user)
        # 実行してエラーが出た場合の処理
        except ValidationError as e:
            # add_error：<フィールド名><エラー> フィールドにエラーを追加して返す
            user_form.add_error('password', e)
            return render(request, 'user/registration.html', context={
                'user_form': user_form,
                'profile_form': profile_form
            })
        user.set_password(user.password)  # パスワードが暗号化されて保存される
        user.save()
        profile = profile_form.save(commit=False)
        # commit=False DB上には保存しないで、モデルインスタンスを返す
        profile.user = user  # onetooneフィールドで紐づいているuserフォームにuserを入れる
        profile.save()
    return render(request, 'user/registration.html', context={
        'user_form': user_form,
        'profile_form': profile_form,
    })


def user_login(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username')
        password = login_form.cleaned_data.get('password')
        # authenticateでユーザー名とパスワードが正しいか確認する
        user = authenticate(username=username, password=password)  # 正しければユーザーインスタンスを返す
        if user:
            # ユーザーが有効な場合
            if user.is_active:
                login(request, user)  # 第２引数にユーザーを指定してログインする
                return redirect('user:index')
            else:
                return HttpResponse('アカウントが有効ではありません')
        else:
            return HttpResponse('ユーザーが存在しません')
    return render(request, 'user/login.html', context={
        'login_form': login_form
    })


@login_required  # ログインしている時だけ実行させるデコレーター
def user_logout(request):
    logout(request)  # ログアウトはlogoutを使うだけ
    return redirect('user:index')


@login_required
def info(request):
    return HttpResponse('ログインしています')

templates/store/item_detail.html
<h1>{{ item.name }}: ¥{{ item.price }}</h1>

templates/store/item_list.html
<table>
    <tr>
        <th>商品名</th>
        <th>価格</th>
    </tr>
    {% for item in items %}
    <tr>
        <td><a href="{% url 'store:item_detail' id=item.id %}">{{ item.name }}</a></td>
        <td>¥{{ item.price }}</td>
    </tr>
    {% endfor %}
</table>

templates/user/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
    </head>
    <body>
        <nav>
            <a href="{% url 'user:index' %}">Home</a>
            <a href="{% url 'admin:index' %}">管理画面</a>
            <!--管理画面へ遷移するには'admin:index'-->
            {% if user.is_authenticated %}
            <a href="{% url 'user:user_logout' %}">ログアウト</a>
            {% else %}
            <a href="{% url 'user:register' %}">登録画面</a>
            <a href="{% url 'user:user_login' %}">ログイン</a>
            {% endif %}
            <a href="{% url 'user:info' %}">インフォメーション</a>
        </nav>
        <div>
            {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

templates/user/index.html
{% extends "user/base.html" %}
{% block content %}
<h1>Login Sample</h1>
{% endblock %}

templates/user/login.html
{% extends "user/base.html" %}
{% block content %}
<h1>ログイン画面</h1>
<form method="POST" action="">
{% csrf_token %}

{{ login_form.as_p }}
<input type="submit" value="ログイン">

</form>
{% endblock %}

templates/user/registration.html
{% extends "user/base.html" %}
{% block content %}
<h1>登録画面</h1>
<!-- 画像を扱うのでenctypeに指定をする -->
<form method="POST" enctype="multipart/form-data" action="">
{% csrf_token %}

{{ user_form.as_p }}
{{ profile_form.as_p }}
<input type="submit" value="登録">

</form>
{% endblock %}

templates/user/user_list.html
<h1>User List</h1>
<!-- storeの方のurlに遷移させてみる -->
<a href="{% url 'store:item_list' %}">商品一覧へ</a>